/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aerolinea.presentacion.Compra;

/**
 *
 * @author Admin2
 */
public class TiqueteView extends javax.swing.JPanel {

    /**
     * Creates new form ComprasView
     */
    public TiqueteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lavion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lavioncalculo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lavion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Avion.png"))); // NOI18N
        add(Lavion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Comprar Asientos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 300, 70));

        jButton1.setText("Comprar");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 110, 30));

        jButton2.setText("Cancelar");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, 100, 30));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 240, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nombre de la Persona");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 180, 30));

        jLabel4.setText("Precio por asiento : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 310, 30));
        add(Lavioncalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 380, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lavion;
    private javax.swing.JLabel Lavioncalculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
